# Generated by Django 5.0.1 on 2024-01-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(upload_to='apply'),
        ),
    ]
