# Generated by Django 5.0.1 on 2024-01-05 00:25

import django.db.models.deletion
import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_apply_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cv',
            field=models.FileField(upload_to=job.models.cv_upload),
        ),
        migrations.AlterField(
            model_name='apply',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='job.job'),
        ),
    ]
